"""FastAPI transport boundary for asynchronous Personal Agent Runs."""

from collections.abc import AsyncIterator, Awaitable, Callable
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, HTTPException, Request, status
from fastapi import Path as FastAPIPath
from fastapi.staticfiles import StaticFiles

from personal_agent.api.rate_limit import RateLimiter
from personal_agent.application.contracts import RunResponse, SubmitMessage
from personal_agent.application.profile import list_topic_groups, load_profile
from personal_agent.application.runs import (
    PersonalRun,
    PersonalRunScheduler,
    PersonalRunStore,
    QueueFullError,
    RunConflictError,
)
from personal_agent.contracts import HealthResponse, ProfileResponse, TopicGroup
from personal_agent.knowledge.store import KnowledgeStore

# Conversation IDs are generated by the frontend as UUIDs but kept permissive for
# local tools; the pattern rejects path separators, exotic characters and
# unbounded lengths that could bloat the SQLite stores.
CONVERSATION_ID_PATTERN = r"^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$"
RUN_ID_PATTERN = r"^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$"


def _run_response(run: PersonalRun) -> RunResponse:
    return RunResponse(
        run_id=run.run_id,
        status=run.status.value,
        answer=run.answer,
        error_message=run.error_message,
    )


def create_app(
    *,
    scheduler: PersonalRunScheduler | None = None,
    run_store: PersonalRunStore | None = None,
    knowledge_store: KnowledgeStore | None = None,
    close_resources: Callable[[], Awaitable[None]] | None = None,
    static_directory: Path | None = None,
    rate_limiter: RateLimiter | None = None,
) -> FastAPI:
    """Create an HTTP app around injected scheduling dependencies."""

    if (scheduler is None) != (run_store is None):
        raise ValueError("scheduler 与 run_store 必须同时提供")

    @asynccontextmanager
    async def lifespan(app: FastAPI) -> AsyncIterator[None]:
        if scheduler is not None:
            await scheduler.start()
        try:
            yield
        finally:
            if scheduler is not None:
                await scheduler.stop()
            if close_resources is not None:
                await close_resources()

    app = FastAPI(title="Personal Agent API", version="0.1.0", lifespan=lifespan)

    @app.get("/health", response_model=HealthResponse, tags=["system"])
    async def health() -> HealthResponse:
        return HealthResponse()

    @app.get("/api/profile", response_model=ProfileResponse, tags=["profile"])
    async def get_profile() -> ProfileResponse:
        if knowledge_store is None:
            raise HTTPException(status_code=503, detail="知识库尚未配置")
        profile = load_profile(knowledge_store)
        if profile is None:
            raise HTTPException(status_code=404, detail="尚未载入身份文档（knowledge/profile.md）")
        return ProfileResponse(**profile.model_dump())

    @app.get("/api/topics", response_model=list[TopicGroup], tags=["profile"])
    async def get_topics() -> list[TopicGroup]:
        if knowledge_store is None:
            raise HTTPException(status_code=503, detail="知识库尚未配置")
        return list_topic_groups(knowledge_store.list_sources())

    @app.post(
        "/api/conversations/{conversation_id}/messages",
        response_model=RunResponse,
        status_code=status.HTTP_202_ACCEPTED,
        tags=["conversations"],
    )
    async def submit_message(
        request: Request,
        payload: SubmitMessage,
        conversation_id: str = FastAPIPath(pattern=CONVERSATION_ID_PATTERN),
    ) -> RunResponse:
        if scheduler is None:
            raise HTTPException(status_code=503, detail="Agent 服务尚未配置")
        client_key = request.client.host if request.client is not None else "unknown"
        if rate_limiter is not None and not rate_limiter.allow(client_key):
            raise HTTPException(status_code=429, detail="请求过于频繁，请稍后再试")
        try:
            run = await scheduler.submit(conversation_id, payload.question.strip())
        except RunConflictError as error:
            raise HTTPException(status_code=409, detail=str(error)) from error
        except QueueFullError as error:
            raise HTTPException(status_code=429, detail=str(error)) from error
        return _run_response(run)

    @app.get("/api/runs/{run_id}", response_model=RunResponse, tags=["runs"])
    async def get_run(run_id: str = FastAPIPath(pattern=RUN_ID_PATTERN)) -> RunResponse:
        if run_store is None:
            raise HTTPException(status_code=503, detail="Agent 服务尚未配置")
        run = run_store.get(run_id)
        if run is None:
            raise HTTPException(status_code=404, detail="未找到 Run")
        return _run_response(run)

    if static_directory is not None:
        if not static_directory.is_dir():
            raise ValueError(f"前端静态目录不存在: {static_directory}")
        app.mount("/", StaticFiles(directory=static_directory, html=True), name="frontend")
    return app


app = create_app()
